import { Inter } from "next/font/google";
import "./globals.css";

const font = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Fizora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="description" content="" />
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
