import { Geist_Mono } from "next/font/google";
import "./globals.css";

const font = Geist_Mono({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Fizora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="description" content="" />
      <body className={`${font.className} antialiased bg-zinc-950 text-white`}>
        {children}
      </body>
    </html>
  );
}
